# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  lottery:
      class: Sanssendecom\LotteryResultBundle\Service\LotteryResultService
  sayisalloto:
      class: Sanssendecom\LotteryResultBundle\Service\LotteryResultService
      arguments: ['SAYISALLOTO']
  sanstopu:
      class: Sanssendecom\LotteryResultBundle\Service\LotteryResultService
      arguments: ['SANSTOPU']
  onnumara:
      class: Sanssendecom\LotteryResultBundle\Service\LotteryResultService
      arguments: ['ONNUMARA']
  superloto:
      class: Sanssendecom\LotteryResultBundle\Service\LotteryResultService
      arguments: ['SUPERLOTO']